spring:
  datasource:
    url: jdbc:postgresql://56.155.9.34:5432/account
    username: postgres
    password: "0714"
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8087
jwt:
  secret: rlaguswjdtlstkskdnslRKdkswdkdlTdj
  expiration: 2592000
auth:
  service:
    url: http://localhost:8092/api/v1/auth