server:
  port: 8085

spring:
  application:
    name: interestCategory
  datasource:
    url: jdbc:postgresql://56.155.9.34:5432/interestcategory
    username: postgres
    password: "0714"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: rlaguswjdtlstkskdnslRKdkswdkdlTdj
  expiration: 2592000

auth:
  service:
    url: http://localhost:8092/api/v1/auth


