server:
  port: 8085

spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/interest_category?serverTimezone=Asia/Seoul
    username: test
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: rlaguswjdtlstkskdnslRKdkswdkdlTdj
  expiration: 2592000


