spring:
  application:
    name: model
  datasource:
    url: jdbc:mysql://localhost:3306/model?serverTimezone=Asia/Seoul
    username: test
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8091
