spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product?serverTimezone=Asia/Seoul
    username: test
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8088

jwt:
  secret: rlaguswjdtlstkskdnslRKdkswdkdlTdj
  expiration: 86400000