spring:
  datasource:
    url: jdbc:postgresql://56.155.9.34:5432/card
    username: postgres
    password: "0714"
  data:
    mongodb:
      uri: mongodb://root:example@ec2-56-155-9-34.ap-northeast-3.compute.amazonaws.com:27017/image?authSource=admin
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082
