spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/card
    username: admin
    password: "0714"
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082
