spring:
  datasource:
    url: jdbc:postgresql://56.155.9.34:5432/card
    username: postgres
    password: "0714"
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082
