spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/auth/**
        - id: transaction-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/transactions/**
        - id: account-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/accounts,/api/v1/banks
        - id: category-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/interest-category/**
            - Method=POST, OPTIONS, GET
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG

