spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment?serverTimezone=Asia/Seoul
    username: test
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8084

jwt:
  secret: rlaguswjdtlstkskdnslRKdkswdkdlTdj
  expiration: 31536000000