spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat?serverTimezone=Asia/Seoul
    username: test
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
server:
  port: 8083
#jwt:
#  secret: asdfaerrwesdfserw2asdfaerrwesdfserw2321
#  expiration: 86400000
